### ISSUE TITLE
Can fail to pull from sshRepo

### ISSUE THREAD

**Issue by b5stephen** [AccountTechnologies/ring#1]
Sometimes Ring fails to pull from an sshRepoUrl that it previously had no problem pulling from earlier in the same day. This error occurs when running Ring with the Visual Studio 2019 extension - so I run a toml file, then stop running it, and then next time I try to run it, this error might occur.

Problem seems intermittent but I have noticed it occurring after a change in VPN connection and I can get around the issue by closing Ring and trying again ... at which point it works.

The following error appears in Rings log files (not that `xx` is redacted code):
``` Initialization failed
System.InvalidOperationException: If sshRepoUrl is used csProj must be a relative path but it is C:\Users\xx\AppData\Local\Temp\ring\repos\core\third-party\ob\provider\./source/xx.WebApi/xx.ProviderService.WebApi.csproj
   at ATech.Ring.DotNet.Cli.Windows.Runnables.Dotnet.DotnetContext.Create[T,C](C config) in C:\Dev\dev\tools\atech-ring\source\ATech.Ring.DotNet.Cli\Windows\Runnables\Dotnet\DotnetContext.cs:line 32
   at ATech.Ring.DotNet.Cli.Windows.Runnables.Dotnet.DotnetRunnableBase`2.InitAsync(CancellationToken token) in C:\Dev\dev\tools\atech-ring\source\ATech.Ring.DotNet.Cli\Windows\Runnables\Dotnet\DotnetRunnable.cs:line 34
   at ATech.Ring.DotNet.Cli.Windows.Runnables.Dotnet.AspNetCoreRunnable.InitAsync(CancellationToken token) in C:\Dev\dev\tools\atech-ring\source\ATech.Ring.DotNet.Cli\Windows\Runnables\Dotnet\AspNetCoreRunnable.cs:line 22
   at ATech.Ring.DotNet.Cli.Abstractions.Runnable`2.InitCoreAsync(CancellationToken token) in C:\Dev\dev\tools\atech-ring\source\ATech.Ring.DotNet.Cli\Abstractions\Runnable.cs:line 187

**Comment by queil** [comment]
@b5stephen It's a bug when runnable gets stopped and then started again.
